openapi: 3.2.0
info:
  description: Close CRM REST API
  title: Close Custom Fields.lead API
  version: 1.0.0
servers:
- url: https://api.close.com/api/v1
security:
- ApiKeyAuth: []
- OAuth2: []
tags:
- name: custom_fields.lead
  externalDocs:
    url: https://developer.close.com/api/resources/custom-fields/custom-fields-lead
paths:
  /custom_field/lead/:
    get:
      operationId: custom_fields.lead_list
      tags:
      - custom_fields.lead
      summary: List Lead Custom Fields
      description: List all the lead custom fields for your organization.
      parameters:
      - $ref: '#/components/parameters/LimitParam'
      - $ref: '#/components/parameters/SkipParam'
      - $ref: '#/components/parameters/FieldsParam'
      responses:
        '200':
          content:
            application/json:
              example:
                data:
                - accepts_multiple_values: false
                  choices: null
                  created_by: user_N6KhMpzHRCYQHdn4gRNIFNN5JExnsrprKA6ekxM63XA
                  date_created: '2014-11-07T05:06:09.422000+00:00'
                  date_updated: '2014-11-10T20:56:16.784000+00:00'
                  description: The number of users in the company
                  editable_with_roles: []
                  id: cf_v6S011I6MqcbVvB2FA5Nk8dr5MkL8sWuCiG8cUleO9c
                  name: '# of users'
                  organization_id: orga_RbREgmiiwcr1w2b4cOnCMQaQPSIFxMqAD2Dh243uxcH
                  type: number
                  updated_by: user_N6KhMpzHRCYQHdn4gRNIFNN5JExnsrprKA6ekxM63XA
                - accepts_multiple_values: true
                  choices:
                  - Apparel
                  - Cars
                  - Cosmetics
                  - IT
                  created_by: user_N6KhMpzHRCYQHdn4gRNIFNN5JExnsrprKA6ekxM63XA
                  date_created: '2014-11-07T05:06:09.423000+00:00'
                  date_updated: '2014-11-12T22:37:55.752000+00:00'
                  description: null
                  editable_with_roles: []
                  id: cf_8wtBWsdRU2Fur7GDnEeXQ7ra2Vu7R4hG1SNYdiEhh0F
                  name: Industry
                  organization_id: orga_RbREgmiiwcr1w2b4cOnCMQaQPSIFxMqAD2Dh243uxcH
                  type: choices
                  updated_by: user_N6KhMpzHRCYQHdn4gRNIFNN5JExnsrprKA6ekxM63XA
                - accepts_multiple_values: false
                  choices: null
                  created_by: user_N6KhMpzHRCYQHdn4gRNIFNN5JExnsrprKA6ekxM63XA
                  date_created: '2014-11-10T23:38:14.535000+00:00'
                  date_updated: '2014-11-10T23:38:14.535000+00:00'
                  description: ID in the company database
                  editable_with_roles:
                  - admin
                  - role_4zhUd9gDKwVv0Bbl2Nk0Ud
                  id: cf_vvHHPVktybLXXqKrUF88PLsGm8sh202oMq3XGy6RcBm
                  name: Internal Database ID
                  organization_id: orga_RbREgmiiwcr1w2b4cOnCMQaQPSIFxMqAD2Dh243uxcH
                  type: text
                  updated_by: user_N6KhMpzHRCYQHdn4gRNIFNN5JExnsrprKA6ekxM63XA
                - accepts_multiple_values: false
                  choices: null
                  created_by: user_N6KhMpzHRCYQHdn4gRNIFNN5JExnsrprKA6ekxM63XA
                  date_created: '2014-11-10T20:56:44.780000+00:00'
                  date_updated: '2014-11-10T20:56:44.780000+00:00'
                  description: null
                  editable_with_roles: []
                  id: cf_xUDvptVqoPQYv5tmRFDxemYOWFT9nlLRqJyQhpcNh4z
                  name: Language Preference
                  organization_id: orga_RbREgmiiwcr1w2b4cOnCMQaQPSIFxMqAD2Dh243uxcH
                  type: text
                  updated_by: user_N6KhMpzHRCYQHdn4gRNIFNN5JExnsrprKA6ekxM63XA
                - accepts_multiple_values: false
                  choices: null
                  created_by: user_N6KhMpzHRCYQHdn4gRNIFNN5JExnsrprKA6ekxM63XA
                  date_created: '2014-11-07T05:06:09.413000+00:00'
                  date_updated: '2014-11-10T20:51:12.636000+00:00'
                  description: The date the trial expires
                  editable_with_roles: []
                  id: cf_MakiQgTzKXrcL8sDJbS2lkuUcA2FxZJAW8Q38ARgwWh
                  name: Trial Due
                  organization_id: orga_RbREgmiiwcr1w2b4cOnCMQaQPSIFxMqAD2Dh243uxcH
                  type: date
                  updated_by: user_N6KhMpzHRCYQHdn4gRNIFNN5JExnsrprKA6ekxM63XA
                - accepts_multiple_values: false
                  choices: null
                  created_by: user_N6KhMpzHRCYQHdn4gRNIFNN5JExnsrprKA6ekxM63XA
                  date_created: '2014-11-07T05:06:09.413000+00:00'
                  date_updated: '2014-11-10T20:51:12.636000+00:00'
                  description: The AE in charge of this account
                  editable_with_roles: []
                  id: cf_MakiQgTzKXrcL8sDJbS2lkuUcA2FxZJAW8Q38ARgwWh
                  name: Owner
                  organization_id: orga_RbREgmiiwcr1w2b4cOnCMQaQPSIFxMqAD2Dh243uxcH
                  type: user
                  updated_by: user_N6KhMpzHRCYQHdn4gRNIFNN5JExnsrprKA6ekxM63XA
                has_more: false
          description: Successful response
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not found
    post:
      operationId: custom_fields.lead_create
      tags:
      - custom_fields.lead
      summary: Create a new Lead Custom Field
      requestBody:
        content:
          application/json:
            example:
              name: '# of users'
              type: number
        required: true
      responses:
        '200':
          content:
            application/json:
              example:
                accepts_multiple_values: false
                choices: null
                created_by: user_N6KhMpzHRCYQHdn4gRNIFNN5JExnsrprKA6ekxM63XA
                date_created: '2014-11-07T05:06:09.422000+00:00'
                date_updated: '2014-11-10T20:56:16.784000+00:00'
                description: The number of users in the company
                editable_with_roles: []
                id: cf_v6S011I6MqcbVvB2FA5Nk8dr5MkL8sWuCiG8cUleO9c
                name: '# of users'
                organization_id: orga_RbREgmiiwcr1w2b4cOnCMQaQPSIFxMqAD2Dh243uxcH
                type: number
                updated_by: user_N6KhMpzHRCYQHdn4gRNIFNN5JExnsrprKA6ekxM63XA
          description: Successful response
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not found
  /custom_field/lead/{id}/:
    get:
      operationId: custom_fields.lead_get
      tags:
      - custom_fields.lead
      summary: Fetch Lead Custom Field's details
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      - $ref: '#/components/parameters/FieldsParam'
      responses:
        '200':
          content:
            application/json:
              example:
                accepts_multiple_values: false
                choices: null
                created_by: user_N6KhMpzHRCYQHdn4gRNIFNN5JExnsrprKA6ekxM63XA
                date_created: '2014-11-07T05:06:09.422000+00:00'
                date_updated: '2014-11-10T20:56:16.784000+00:00'
                description: The number of users in the company
                editable_with_roles: []
                id: cf_v6S011I6MqcbVvB2FA5Nk8dr5MkL8sWuCiG8cUleO9c
                name: '# of users'
                organization_id: orga_RbREgmiiwcr1w2b4cOnCMQaQPSIFxMqAD2Dh243uxcH
                type: number
                updated_by: user_N6KhMpzHRCYQHdn4gRNIFNN5JExnsrprKA6ekxM63XA
          description: Successful response
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not found
    put:
      operationId: custom_fields.lead_update
      tags:
      - custom_fields.lead
      summary: Update a Lead Custom Field
      description: 'You can rename it, change its type, change whether it accepts multiple values or not, change whether editing its values is restricted to specific Roles, or update the options for a "choices" field type. The updated name will immediately appear in the Close UI and only valid values for the updated `type` will be returned by the Lead API.


        Some of the type changes need to convert all of the existing values for a given Custom Field to the new type. When this is required, the response will include an additional `converting_to_type` field. When the conversion is done, `converting_to_type` will no longer be returned.'
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            example:
              name: Number of users
              type: text
        required: true
      responses:
        '200':
          content:
            application/json:
              example:
                accepts_multiple_values: false
                choices: null
                created_by: user_N6KhMpzHRCYQHdn4gRNIFNN5JExnsrprKA6ekxM63XA
                date_created: '2014-11-07T05:06:09.422000+00:00'
                date_updated: '2014-11-10T20:56:16.784000+00:00'
                description: The number of users in the company
                editable_with_roles: []
                id: cf_v6S011I6MqcbVvB2FA5Nk8dr5MkL8sWuCiG8cUleO9c
                name: Number of users
                organization_id: orga_RbREgmiiwcr1w2b4cOnCMQaQPSIFxMqAD2Dh243uxcH
                type: text
                updated_by: user_N6KhMpzHRCYQHdn4gRNIFNN5JExnsrprKA6ekxM63XA
          description: Successful response
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not found
    delete:
      operationId: custom_fields.lead_delete
      tags:
      - custom_fields.lead
      summary: Delete a Lead Custom Field
      description: Delete a lead custom field. The field will immediately disappear from API responses and values on existing leads will be permanently removed.
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not found
components:
  parameters:
    LimitParam:
      description: Number of results to return.
      in: query
      name: _limit
      required: false
      schema:
        default: 100
        type: integer
    FieldsParam:
      description: Comma-separated list of fields to include in the response.
      in: query
      name: _fields
      required: false
      schema:
        type: string
    SkipParam:
      description: Number of results to skip before returning, for pagination.
      in: query
      name: _skip
      required: false
      schema:
        default: 0
        type: integer
  securitySchemes:
    ApiKeyAuth:
      description: Use your API key as the username and leave the password empty.
      scheme: basic
      type: http
    OAuth2:
      flows:
        authorizationCode:
          authorizationUrl: https://app.close.com/oauth2/authorize/
          scopes:
            all.full_access: Full access to all resources
            offline_access: Request a refresh token
          tokenUrl: https://api.close.com/oauth2/token/
      type: oauth2
