openapi: 3.2.0
info:
  description: Close CRM REST API
  title: Close Pipelines API
  version: 1.0.0
servers:
- url: https://api.close.com/api/v1
security:
- ApiKeyAuth: []
- OAuth2: []
tags:
- name: pipelines
  externalDocs:
    url: https://developer.close.com/api/resources/pipelines
paths:
  /pipeline/:
    get:
      operationId: pipelines_list
      tags:
      - pipelines
      summary: List Pipelines for your organization
      responses:
        '200':
          content:
            application/json:
              example:
                data:
                - created_by: user_N6KhMpzHRCYQHdn4gRNIFNN5JExnsrprKA6ekxM63XA
                  date_created: '2019-11-04T11:04:13.014979'
                  date_updated: '2019-11-13T14:12:13.051542'
                  id: pipe_6gV01if4wo7r2YTVQDWP2j
                  name: Sales
                  organization_id: orga_RbREgmiiwcr1w2b4cOnCMQaQPSIFxMqAD2Dh243uxcH
                  statuses:
                  - id: stat_3PB2sedHBCjwuBImAEwgHOo858f2j41lpROkcl51Fzp
                    label: Active
                    type: active
                  - id: stat_IOCtLYbAclJ8XAcb3yLUhQA3zlmjtXz8JMBLyXnNMF8
                    label: Won
                    type: won
                  - id: stat_3mmBOyMmaG8yc4DmAPp9WmgbjhVctVLlnd9gmvWxBe2
                    label: Lost
                    type: lost
                  updated_by: user_N6KhMpzHRCYQHdn4gRNIFNN5JExnsrprKA6ekxM63XA
          description: Successful response
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not found
    post:
      operationId: pipelines_create
      tags:
      - pipelines
      summary: Create a Pipeline
      requestBody:
        content:
          application/json:
            example:
              name: Success
        required: true
      responses:
        '201':
          content:
            application/json:
              example:
                created_by: user_N6KhMpzHRCYQHdn4gRNIFNN5JExnsrprKA6ekxM63XA
                date_created: '2019-11-04T11:04:13.014979'
                date_updated: '2019-11-13T14:12:13.051542'
                id: pipe_6gV01if4wo7r2YTVQDWP2j
                name: Success
                organization_id: orga_RbREgmiiwcr1w2b4cOnCMQaQPSIFxMqAD2Dh243uxcH
                statuses: []
                updated_by: user_N6KhMpzHRCYQHdn4gRNIFNN5JExnsrprKA6ekxM63XA
          description: Successful response
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not found
  /pipeline/{id}/:
    get:
      operationId: pipelines_get
      tags:
      - pipelines
      summary: Fetch a single Pipeline
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              example:
                created_by: user_N6KhMpzHRCYQHdn4gRNIFNN5JExnsrprKA6ekxM63XA
                date_created: '2019-11-04T11:04:13.014979'
                date_updated: '2019-11-13T14:12:13.051542'
                id: pipe_6gV01if4wo7r2YTVQDWP2j
                name: Sales
                organization_id: orga_RbREgmiiwcr1w2b4cOnCMQaQPSIFxMqAD2Dh243uxcH
                statuses:
                - id: stat_3PB2sedHBCjwuBImAEwgHOo858f2j41lpROkcl51Fzp
                  label: Active
                  type: active
                - id: stat_IOCtLYbAclJ8XAcb3yLUhQA3zlmjtXz8JMBLyXnNMF8
                  label: Won
                  type: won
                - id: stat_3mmBOyMmaG8yc4DmAPp9WmgbjhVctVLlnd9gmvWxBe2
                  label: Lost
                  type: lost
                updated_by: user_N6KhMpzHRCYQHdn4gRNIFNN5JExnsrprKA6ekxM63XA
          description: Successful response
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not found
    put:
      operationId: pipelines_update
      tags:
      - pipelines
      summary: Update a Pipeline
      description: "You can use this endpoint to:\n\n* Rename a Pipeline.\n* Reorder Opportunity Statuses within a Pipeline.\n* Move an Opportunity Status from a different Pipeline into this one.\n    * To do so, include `{\"id\": \"id_of_the_status_from_another_pipeline\"}` in the `statuses` list."
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            example:
              name: Updated Name
              statuses:
              - id: stat_3mmBOyMmaG8yc4DmAPp9WmgbjhVctVLlnd9gmvWxBe2
              - id: stat_IOCtLYbAclJ8XAcb3yLUhQA3zlmjtXz8JMBLyXnNMF8
              - id: stat_3PB2sedHBCjwuBImAEwgHOo858f2j41lpROkcl51Fzp
        required: true
      responses:
        '200':
          content:
            application/json:
              example:
                created_by: user_N6KhMpzHRCYQHdn4gRNIFNN5JExnsrprKA6ekxM63XA
                date_created: '2019-11-04T11:04:13.014979'
                date_updated: '2019-11-15T14:12:13.051542'
                id: pipe_6gV01if4wo7r2YTVQDWP2j
                name: Updated Name
                organization_id: orga_RbREgmiiwcr1w2b4cOnCMQaQPSIFxMqAD2Dh243uxcH
                statuses:
                - id: stat_3mmBOyMmaG8yc4DmAPp9WmgbjhVctVLlnd9gmvWxBe2
                  label: Lost
                  type: lost
                - id: stat_IOCtLYbAclJ8XAcb3yLUhQA3zlmjtXz8JMBLyXnNMF8
                  label: Won
                  type: won
                - id: stat_3PB2sedHBCjwuBImAEwgHOo858f2j41lpROkcl51Fzp
                  label: Active
                  type: active
                updated_by: user_N6KhMpzHRCYQHdn4gRNIFNN5JExnsrprKA6ekxM63XA
          description: Successful response
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not found
    delete:
      operationId: pipelines_delete
      tags:
      - pipelines
      summary: Delete a Pipeline
      description: Deletion is only allowed if the Pipeline doesn't contain any Opportunity Statuses. Delete all statuses first or move them to another pipeline.
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '204':
          description: No content
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not found
components:
  securitySchemes:
    ApiKeyAuth:
      description: Use your API key as the username and leave the password empty.
      scheme: basic
      type: http
    OAuth2:
      flows:
        authorizationCode:
          authorizationUrl: https://app.close.com/oauth2/authorize/
          scopes:
            all.full_access: Full access to all resources
            offline_access: Request a refresh token
          tokenUrl: https://api.close.com/oauth2/token/
      type: oauth2
