openapi: 3.2.0
info:
  description: Close CRM REST API
  title: Close Activities.opportunity Status Changes API
  version: 1.0.0
servers:
- url: https://api.close.com/api/v1
security:
- ApiKeyAuth: []
- OAuth2: []
tags:
- name: activities.opportunity_status_changes
  externalDocs:
    url: https://developer.close.com/api/resources/activities/opportunity-status-changes
paths:
  /activity/status_change/opportunity/:
    get:
      operationId: activities.opportunity_status_changes_list
      tags:
      - activities.opportunity_status_changes
      summary: List or filter all OpportunityStatusChange activities
      parameters:
      - $ref: '#/components/parameters/LimitParam'
      - $ref: '#/components/parameters/SkipParam'
      - $ref: '#/components/parameters/ActivityFilters_IdInParam'
      - $ref: '#/components/parameters/ActivityFilters_LeadIdParam'
      - $ref: '#/components/parameters/ActivityFilters_ContactIdParam'
      - $ref: '#/components/parameters/ActivityFilters_UserIdParam'
      - $ref: '#/components/parameters/ActivityFilters_OrganizationIdParam'
      - $ref: '#/components/parameters/ActivityFilters_TypeParam'
      - $ref: '#/components/parameters/ActivityFilters_DateCreatedGteParam'
      - $ref: '#/components/parameters/ActivityFilters_DateCreatedLteParam'
      - $ref: '#/components/parameters/ActivityFilters_DateCreatedGtParam'
      - $ref: '#/components/parameters/ActivityFilters_DateCreatedLtParam'
      - $ref: '#/components/parameters/ActivityFilters_ActivityAtGteParam'
      - $ref: '#/components/parameters/ActivityFilters_ActivityAtLteParam'
      - $ref: '#/components/parameters/ActivityFilters_ActivityAtGtParam'
      - $ref: '#/components/parameters/ActivityFilters_ActivityAtLtParam'
      - in: query
        name: opportunity_id
        required: false
        schema:
          title: Opportunity ID
          default: null
          anyOf:
          - type: string
          - type: 'null'
      - $ref: '#/components/parameters/FieldsParam'
      responses:
        '200':
          content:
            application/json:
              example:
                data:
                - _type: OpportunityStatusChange
                  activity_at: '2013-08-23T21:21:11.862000+00:00'
                  contact_id: null
                  created_by: user_N6KhMpzHRCYQHdn4gRNIFNN5JExnsrprKA6ekxM63XA
                  created_by_name: Anthony Nemitz
                  date_created: '2013-08-23T21:21:11.862000+00:00'
                  date_updated: '2013-08-23T21:21:11.862000+00:00'
                  id: acti_CAI2lO44gRLMIvgsKfPZghRyuv1h8S3l7c4cDznXukd
                  lead_id: lead_0VaTsortzKpCv1ik6hbNoudduuD0m2Itevet0fKX39G
                  new_pipeline_id: pipe_6gV01if4wo7r2YTVQDWP2j
                  new_pipeline_name: Sales
                  new_status_id: stat_DetsqwxFOOHx2JnhqtovutN3zeuARGfzB21x5t1W88G
                  new_status_label: Won
                  new_status_type: won
                  old_pipeline_id: pipe_6gV01if4wo7r2YTVQDWP2j
                  old_pipeline_name: Sales
                  old_status_id: stat_ue534UFRaocoMJJA9CYCwnMsRJP2qt6YGnpZOAx7ckK
                  old_status_label: Active
                  old_status_type: active
                  opportunity_confidence: 100
                  opportunity_date_won: '2013-08-23T00:00:00+00:00'
                  opportunity_id: oppo_fn2kSFXS06akJ7XisR7vQQeObyK4upCc43RiAx1Vyz6
                  opportunity_value: 0
                  opportunity_value_currency: USD
                  opportunity_value_formatted: null
                  opportunity_value_period: one_time
                  organization_id: orga_RbREgmiiwcr1w2b4cOnCMQaQPSIFxMqAD2Dh243uxcH
                  updated_by: user_N6KhMpzHRCYQHdn4gRNIFNN5JExnsrprKA6ekxM63XA
                  updated_by_name: Anthony Nemitz
                  user_id: user_N6KhMpzHRCYQHdn4gRNIFNN5JExnsrprKA6ekxM63XA
                  user_name: Anthony Nemitz
                  users: []
                has_more: false
              schema:
                type: object
                properties:
                  data:
                    items:
                      $ref: '#/components/schemas/OpportunityStatusChangeActivity'
                    type: array
                  has_more:
                    type: boolean
                required:
                - data
                - has_more
          description: Successful response
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not found
    post:
      operationId: activities.opportunity_status_changes_create
      tags:
      - activities.opportunity_status_changes
      summary: Create a new OpportunityStatusChange activity
      description: Creating an opportunity status change does not change the opportunity's status. It only logs the status change event. This should only be used to import historical status changes from another system.
      requestBody:
        content:
          application/json:
            example:
              date_created: '2013-08-23T20:57:45.956000+00:00'
              lead_id: lead_fioU1Nk5LC0H0iei9XBGHW2CFZU0yeP2zZCJQP9pC4m
              new_status_id: stat_DetsqwxFOOHx2JnhqtovutN3zeuARGfzB21x5t1W88G
              old_status_id: stat_ue534UFRaocoMJJA9CYCwnMsRJP2qt6YGnpZOAx7ckK
              opportunity_id: oppo_fn2kSFXS06akJ7XisR7vQQeObyK4upCc43RiAx1Vyz6
        required: true
      responses:
        '200':
          content:
            application/json:
              example:
                _type: OpportunityStatusChange
                activity_at: '2013-08-23T21:21:11.862000+00:00'
                contact_id: null
                created_by: user_N6KhMpzHRCYQHdn4gRNIFNN5JExnsrprKA6ekxM63XA
                created_by_name: Anthony Nemitz
                date_created: '2013-08-23T21:21:11.862000+00:00'
                date_updated: '2013-08-23T21:21:11.862000+00:00'
                id: acti_CAI2lO44gRLMIvgsKfPZghRyuv1h8S3l7c4cDznXukd
                lead_id: lead_0VaTsortzKpCv1ik6hbNoudduuD0m2Itevet0fKX39G
                new_pipeline_id: pipe_6gV01if4wo7r2YTVQDWP2j
                new_pipeline_name: Sales
                new_status_id: stat_DetsqwxFOOHx2JnhqtovutN3zeuARGfzB21x5t1W88G
                new_status_label: Won
                new_status_type: won
                old_pipeline_id: pipe_6gV01if4wo7r2YTVQDWP2j
                old_pipeline_name: Sales
                old_status_id: stat_ue534UFRaocoMJJA9CYCwnMsRJP2qt6YGnpZOAx7ckK
                old_status_label: Active
                old_status_type: active
                opportunity_confidence: 100
                opportunity_date_won: '2013-08-23T00:00:00+00:00'
                opportunity_id: oppo_fn2kSFXS06akJ7XisR7vQQeObyK4upCc43RiAx1Vyz6
                opportunity_value: 0
                opportunity_value_currency: USD
                opportunity_value_formatted: null
                opportunity_value_period: one_time
                organization_id: orga_RbREgmiiwcr1w2b4cOnCMQaQPSIFxMqAD2Dh243uxcH
                updated_by: user_N6KhMpzHRCYQHdn4gRNIFNN5JExnsrprKA6ekxM63XA
                updated_by_name: Anthony Nemitz
                user_id: user_N6KhMpzHRCYQHdn4gRNIFNN5JExnsrprKA6ekxM63XA
                user_name: Anthony Nemitz
                users: []
              schema:
                $ref: '#/components/schemas/OpportunityStatusChangeActivity'
          description: Successful response
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not found
  /activity/status_change/opportunity/{id}/:
    get:
      operationId: activities.opportunity_status_changes_get
      tags:
      - activities.opportunity_status_changes
      summary: Get a single OpportunityStatusChange activity
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      - $ref: '#/components/parameters/FieldsParam'
      responses:
        '200':
          content:
            application/json:
              example:
                _type: OpportunityStatusChange
                activity_at: '2013-08-23T21:21:11.862000+00:00'
                contact_id: null
                created_by: user_N6KhMpzHRCYQHdn4gRNIFNN5JExnsrprKA6ekxM63XA
                created_by_name: Anthony Nemitz
                date_created: '2013-08-23T21:21:11.862000+00:00'
                date_updated: '2013-08-23T21:21:11.862000+00:00'
                id: acti_CAI2lO44gRLMIvgsKfPZghRyuv1h8S3l7c4cDznXukd
                lead_id: lead_0VaTsortzKpCv1ik6hbNoudduuD0m2Itevet0fKX39G
                new_pipeline_id: pipe_6gV01if4wo7r2YTVQDWP2j
                new_pipeline_name: Sales
                new_status_id: stat_DetsqwxFOOHx2JnhqtovutN3zeuARGfzB21x5t1W88G
                new_status_label: Won
                new_status_type: won
                old_pipeline_id: pipe_6gV01if4wo7r2YTVQDWP2j
                old_pipeline_name: Sales
                old_status_id: stat_ue534UFRaocoMJJA9CYCwnMsRJP2qt6YGnpZOAx7ckK
                old_status_label: Active
                old_status_type: active
                opportunity_confidence: 100
                opportunity_date_won: '2013-08-23T00:00:00+00:00'
                opportunity_id: oppo_fn2kSFXS06akJ7XisR7vQQeObyK4upCc43RiAx1Vyz6
                opportunity_value: 0
                opportunity_value_currency: USD
                opportunity_value_formatted: null
                opportunity_value_period: one_time
                organization_id: orga_RbREgmiiwcr1w2b4cOnCMQaQPSIFxMqAD2Dh243uxcH
                updated_by: user_N6KhMpzHRCYQHdn4gRNIFNN5JExnsrprKA6ekxM63XA
                updated_by_name: Anthony Nemitz
                user_id: user_N6KhMpzHRCYQHdn4gRNIFNN5JExnsrprKA6ekxM63XA
                user_name: Anthony Nemitz
                users: []
              schema:
                $ref: '#/components/schemas/OpportunityStatusChangeActivity'
          description: Successful response
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not found
    delete:
      operationId: activities.opportunity_status_changes_delete
      tags:
      - activities.opportunity_status_changes
      summary: Delete a single OpportunityStatusChange activity
      description: 'Deleting an OpportunityStatusChange does not change the status of the Opportunity. It only removes the status change event from the Lead''s activity feed.


        It should only be used if the status change is irrelevant (such as records for a change that has been reverted) and having it in the activity feed is causing integration problems with another system.'
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not found
components:
  parameters:
    ActivityFilters_DateCreatedGteParam:
      in: query
      name: date_created__gte
      required: false
      schema:
        title: Date Created (>=)
        anyOf:
        - type: string
          format: date-time
        - type: string
          format: date
    ActivityFilters_ActivityAtLteParam:
      in: query
      name: activity_at__lte
      required: false
      schema:
        title: Activity At (<=)
        anyOf:
        - type: string
          format: date-time
        - type: string
          format: date
    ActivityFilters_TypeParam:
      description: Filter by activity type, e.g. Call (comma-separated)
      in: query
      name: _type
      required: false
      schema:
        title: Type
        default: null
        anyOf:
        - type: array
          items:
            type: string
        - type: 'null'
    ActivityFilters_OrganizationIdParam:
      in: query
      name: organization_id
      required: false
      schema:
        title: Organization ID
        default: null
        anyOf:
        - type: string
        - type: 'null'
    ActivityFilters_LeadIdParam:
      description: Filter by lead IDs (comma-separated)
      in: query
      name: lead_id
      required: false
      schema:
        title: Lead ID
        default: null
        anyOf:
        - type: array
          items:
            type: string
        - type: 'null'
    ActivityFilters_ActivityAtLtParam:
      in: query
      name: activity_at__lt
      required: false
      schema:
        title: Activity At (<)
        anyOf:
        - type: string
          format: date-time
        - type: string
          format: date
    ActivityFilters_ActivityAtGteParam:
      in: query
      name: activity_at__gte
      required: false
      schema:
        title: Activity At (>=)
        anyOf:
        - type: string
          format: date-time
        - type: string
          format: date
    ActivityFilters_UserIdParam:
      description: Filter by user IDs (comma-separated)
      in: query
      name: user_id
      required: false
      schema:
        title: User ID
        default: null
        anyOf:
        - type: array
          items:
            type: string
        - type: 'null'
    ActivityFilters_ContactIdParam:
      description: Filter by contact IDs (comma-separated)
      in: query
      name: contact_id
      required: false
      schema:
        title: Contact ID
        default: null
        anyOf:
        - type: array
          items:
            type: string
        - type: 'null'
    LimitParam:
      description: Number of results to return.
      in: query
      name: _limit
      required: false
      schema:
        default: 100
        type: integer
    SkipParam:
      description: Number of results to skip before returning, for pagination.
      in: query
      name: _skip
      required: false
      schema:
        default: 0
        type: integer
    ActivityFilters_IdInParam:
      description: Filter by activity IDs (comma-separated)
      in: query
      name: id__in
      required: false
      schema:
        title: ID In
        default: null
        anyOf:
        - type: array
          items:
            type: string
        - type: 'null'
    FieldsParam:
      description: Comma-separated list of fields to include in the response.
      in: query
      name: _fields
      required: false
      schema:
        type: string
    ActivityFilters_DateCreatedLtParam:
      in: query
      name: date_created__lt
      required: false
      schema:
        title: Date Created (<)
        anyOf:
        - type: string
          format: date-time
        - type: string
          format: date
    ActivityFilters_ActivityAtGtParam:
      in: query
      name: activity_at__gt
      required: false
      schema:
        title: Activity At (>)
        anyOf:
        - type: string
          format: date-time
        - type: string
          format: date
    ActivityFilters_DateCreatedGtParam:
      in: query
      name: date_created__gt
      required: false
      schema:
        title: Date Created (>)
        anyOf:
        - type: string
          format: date-time
        - type: string
          format: date
    ActivityFilters_DateCreatedLteParam:
      in: query
      name: date_created__lte
      required: false
      schema:
        title: Date Created (<=)
        anyOf:
        - type: string
          format: date-time
        - type: string
          format: date
  schemas:
    OpportunityStatusType:
      title: OpportunityStatusType
      type: string
      enum:
      - won
      - lost
      - active
    OpportunityStatusChangeActivity:
      title: OpportunityStatusChangeActivity
      type: object
      properties:
        _type:
          title: Type
          type: string
        activity_at:
          title: Activity At
          anyOf:
          - type: string
            format: date-time
          - type: 'null'
        contact_id:
          title: Contact ID
          anyOf:
          - type: string
          - type: 'null'
        created_by:
          title: Created By
          anyOf:
          - type: string
          - type: 'null'
        created_by_name:
          title: Created By Name
          default: null
          anyOf:
          - type: string
          - type: 'null'
        date_created:
          title: Date Created
          type: string
          format: date-time
        date_updated:
          title: Date Updated
          type: string
          format: date-time
        id:
          title: ID
          type: string
        lead_id:
          title: Lead ID
          anyOf:
          - type: string
          - type: 'null'
        new_pipeline_id:
          title: New Pipeline ID
          type: string
        new_pipeline_name:
          title: New Pipeline Name
          type: string
        new_status_id:
          title: New Status ID
          type: string
        new_status_label:
          title: New Status Label
          type: string
        new_status_type:
          title: New Status Type
          $ref: '#/components/schemas/OpportunityStatusType'
        old_pipeline_id:
          title: Old Pipeline ID
          type: string
        old_pipeline_name:
          title: Old Pipeline Name
          type: string
        old_status_id:
          title: Old Status ID
          type: string
        old_status_label:
          title: Old Status Label
          type: string
        old_status_type:
          title: Old Status Type
          $ref: '#/components/schemas/OpportunityStatusType'
        opportunity_confidence:
          title: Opportunity Confidence
          anyOf:
          - type: integer
          - type: 'null'
        opportunity_date_won:
          title: Opportunity Date Won
          anyOf:
          - type: string
            format: date-time
          - type: 'null'
        opportunity_id:
          title: Opportunity ID
          anyOf:
          - type: string
          - type: 'null'
        opportunity_value:
          title: Opportunity Value
          anyOf:
          - type: integer
          - type: 'null'
        opportunity_value_currency:
          title: Opportunity Value Currency
          anyOf:
          - type: string
          - type: 'null'
        opportunity_value_formatted:
          title: Opportunity Value Formatted
          anyOf:
          - type: string
          - type: 'null'
        opportunity_value_period:
          title: Opportunity Value Period
          anyOf:
          - $ref: '#/components/schemas/OpportunityValuePeriod'
          - type: 'null'
        organization_id:
          title: Organization ID
          type: string
        updated_by:
          title: Updated By
          anyOf:
          - type: string
          - type: 'null'
        updated_by_name:
          title: Updated By Name
          default: null
          anyOf:
          - type: string
          - type: 'null'
        user_id:
          title: User ID
          anyOf:
          - type: string
          - type: 'null'
        user_name:
          title: User Name
          default: null
          anyOf:
          - type: string
          - type: 'null'
        users:
          title: Users
          type: array
          items:
            type: string
      required:
      - _type
      - activity_at
      - contact_id
      - created_by
      - date_created
      - date_updated
      - id
      - lead_id
      - new_status_id
      - old_status_id
      - opportunity_id
      - organization_id
      - updated_by
      - user_id
      - users
    OpportunityValuePeriod:
      title: OpportunityValuePeriod
      type: string
      enum:
      - one_time
      - monthly
      - annual
  securitySchemes:
    ApiKeyAuth:
      description: Use your API key as the username and leave the password empty.
      scheme: basic
      type: http
    OAuth2:
      flows:
        authorizationCode:
          authorizationUrl: https://app.close.com/oauth2/authorize/
          scopes:
            all.full_access: Full access to all resources
            offline_access: Request a refresh token
          tokenUrl: https://api.close.com/oauth2/token/
      type: oauth2
